# Exploración inicial de datasets

In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("nilkamalsaha/crm-sales-opportunities-on-google-sheets")

print("Path to dataset files:", path)

Downloading to /root/.cache/kagglehub/datasets/nilkamalsaha/crm-sales-opportunities-on-google-sheets/1.archive...

100%|██████████| 143k/143k [00:00<00:00, 57.2MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/nilkamalsaha/crm-sales-opportunities-on-google-sheets/versions/1

In [5]:
import os

for file in os.listdir(path):
    print(file)

data_dictionary.csv
accounts.csv
sales_teams.csv
products.csv
sales_pipeline.csv

In [6]:
import pandas as pd

sales_pipeline = pd.read_csv(f"{path}/sales_pipeline.csv")
accounts = pd.read_csv(f"{path}/accounts.csv")
sales_teams = pd.read_csv(f"{path}/sales_teams.csv")
products = pd.read_csv(f"{path}/products.csv")

In [8]:
print("SALES PIPELINE")
display(sales_pipeline.head())

print("ACCOUNTS")
display(accounts.head())

print("SALES TEAMS")
display(sales_teams.head())

print("PRODUCTS")
display(products.head())

SALES PIPELINE

,opportunity_id,sales_agent,product,account,deal_stage,engage_date,close_date,close_value
0,1C1I7A6R,Moses Frase,GTX Plus Basic,Cancity,Won,2016-10-20,2017-03-01,1054.0
1,Z063OYW0,Darcel Schlecht,GTXPro,Isdom,Won,2016-10-25,2017-03-11,4514.0
2,EC4QE1BX,Darcel Schlecht,MG Special,Cancity,Won,2016-10-25,2017-03-07,50.0
3,MV1LWRNH,Moses Frase,GTX Basic,Codehow,Won,2016-10-25,2017-03-09,588.0
4,PE84CX4O,Zane Levy,GTX Basic,Hatfan,Won,2016-10-25,2017-03-02,517.0

ACCOUNTS

,account,sector,year_established,revenue,employees,office_location,subsidiary_of
0,Acme Corporation,technolgy,1996,1100.04,2822,United States,NaN
1,Betasoloin,medical,1999,251.41,495,United States,NaN
2,Betatech,medical,1986,647.18,1185,Kenya,NaN
3,Bioholding,medical,2012,587.34,1356,Philipines,NaN
4,Bioplex,medical,1991,326.82,1016,United States,NaN

SALES TEAMS

         sales_agent           manager regional_office
0      Anna Snelling  Dustin Brinkmann         Central
1     Cecily Lampkin  Dustin Brinkmann         Central
2  Versie Hillebrand  Dustin Brinkmann         Central
3    Lajuana Vencill  Dustin Brinkmann         Central
4        Moses Frase  Dustin Brinkmann         Central

PRODUCTS

        product series  sales_price
0     GTX Basic    GTX          550
1       GTX Pro    GTX         4821
2    MG Special     MG           55
3   MG Advanced     MG         3393
4  GTX Plus Pro    GTX         5482

In [9]:
datasets = {
    "sales_pipeline": sales_pipeline,
    "accounts": accounts,
    "sales_teams": sales_teams,
    "products": products
}

for name, df in datasets.items():
    print(f"{name}: {df.shape}")

sales_pipeline: (8800, 8)
accounts: (85, 7)
sales_teams: (35, 3)
products: (7, 3)

In [10]:
import pandas as pd

# Cargar datasets
sales_pipeline = pd.read_csv(f"{path}/sales_pipeline.csv")
accounts = pd.read_csv(f"{path}/accounts.csv")
sales_teams = pd.read_csv(f"{path}/sales_teams.csv")
products = pd.read_csv(f"{path}/products.csv")

# Join con accounts
df = sales_pipeline.merge(
    accounts,
    on="account",
    how="left"
)

# Join con sales teams
df = df.merge(
    sales_teams,
    on="sales_agent",
    how="left"
)

# Join con products
df = df.merge(
    products,
    on="product",
    how="left"
)

# Ver resultado
df.head()

,opportunity_id,sales_agent,product,account,deal_stage,engage_date,close_date,close_value,sector,year_established,revenue,employees,office_location,subsidiary_of,manager,regional_office,series,sales_price
0,1C1I7A6R,Moses Frase,GTX Plus Basic,Cancity,Won,2016-10-20,2017-03-01,1054.0,retail,2001.0,718.62,2448.0,United States,NaN,Dustin Brinkmann,Central,GTX,1096.0
1,Z063OYW0,Darcel Schlecht,GTXPro,Isdom,Won,2016-10-25,2017-03-11,4514.0,medical,2002.0,3178.24,4540.0,United States,NaN,Melvin Marxen,Central,NaN,NaN
2,EC4QE1BX,Darcel Schlecht,MG Special,Cancity,Won,2016-10-25,2017-03-07,50.0,retail,2001.0,718.62,2448.0,United States,NaN,Melvin Marxen,Central,MG,55.0
3,MV1LWRNH,Moses Frase,GTX Basic,Codehow,Won,2016-10-25,2017-03-09,588.0,software,1998.0,2714.90,2641.0,United States,Acme Corporation,Dustin Brinkmann,Central,GTX,550.0
4,PE84CX4O,Zane Levy,GTX Basic,Hatfan,Won,2016-10-25,2017-03-02,517.0,services,1982.0,792.46,1299.0,United States,NaN,Summer Sewald,West,GTX,550.0

In [11]:
df.shape

(8800, 18)

In [12]:
df.columns

Index(['opportunity_id', 'sales_agent', 'product', 'account', 'deal_stage',
       'engage_date', 'close_date', 'close_value', 'sector',
       'year_established', 'revenue', 'employees', 'office_location',
       'subsidiary_of', 'manager', 'regional_office', 'series', 'sales_price'],
      dtype='object')

In [13]:
df.isnull().sum()

opportunity_id         0
sales_agent            0
product                0
account             1425
deal_stage             0
engage_date          500
close_date          2089
close_value         2089
sector              1425
year_established    1425
revenue             1425
employees           1425
office_location     1425
subsidiary_of       7508
manager                0
regional_office        0
series              1480
sales_price         1480
dtype: int64